#!/usr/bin/env ruby
# Copyright 2015 Christian Theil Have
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
#	The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
require 'bio-samtools'
require 'optparse'
require 'zlib'
require 'pp'

options = {}

OptionParser.new do |opts|
	opts.on( '-h', '--help', 'Display this message' ) do
		STDERR.puts opts
		exit
	end

	opts.on("-v", "--vcf file.vcf", "VCF file to extract from") do |file|
		options[:vcf] = file 
	end

	opts.on("-0", "--012 file.012", "012 Genotype table") do |file|
		options[:geno] = file
	end
end.parse!

begin
	throw("Missing --vcf input file. Cannot proceed!") unless options.include?(:vcf) 
	[ :geno ].each { |i| options[i] = options[:vcf] + "." + i.to_s unless options.include?(i) }

	pp options

	columns = []
	variants_processed=0
	File.open(options[:vcf]) do |file|
		file.each do |line|
			if line =~ /^#CHROM.*/ then
				fields = line.chomp.split("\t")
				9.times { fields.shift }
				columns[0] = ['particid'] + fields
			end
			next if line =~ /^#.*/
			variants_processed = variants_processed + 1
			puts "variants processed: #{variants_processed}" if variants_processed % 100 == 0
			vcfline=Bio::DB::Vcf.new(line)

			columns << [ vcfline.id ]



			vcfline.samples.each do |id,geno|

				columns[columns.size-1] << if geno["GT"] == "./."
					"NA"
				elsif geno["GT"] == "0/0"
					0
				elsif geno["GT"] == "0/1"
					1
				elsif geno["GT"] == "1/1"
					2
				end

				#columns[columns.size-1] << (geno["GT"].gsub("/","|").split("|").map {|i| i.to_i }).collect { |i,j| i+j }~
			end

		end
	end 

	File.open(options[:geno], "w") do |file|
		columns.transpose.each { |r| file.puts r.join("\t") }
	end
rescue => e
	STDERR.puts e.to_s.gsub("uncaught throw", "ERROR:")
end
